### ISSUE TITLE
Make your variables private 

### ISSUE THREAD

**Issue by Jenssile** [MercantecData/portfolio-NicklasN757#3]
Make your variables private as it is very bad practices to make all variables public, only the variables that **NEED** to be public should be.

**Comment by NicklasN757** [comment]
Kommer ikke til at ske. Sorry måske næste gang.

**Comment by MadsBock** [comment]
Hvorfor kommer det ikke til at ske?

**Comment by NicklasN757** [comment]
@adamdanyx 
Vi er gået vider til clientSite og fordi jeg bruger alle de variabler jeg har skrevet, altså retter sagt alle dem som er public bliver brugt. Hvis der skal laves nogen om må I godt speciefer hvad for nogen det er, ellers ville jeg mene at det er lavet så godt det kan gøres?

**Comment by MadsBock** [comment]
Ja det fint
